import type { ModuleContent, ModuleId } from './types'

export const NICKNAMES = [
  'Sunny Crab',
  'Coral Fox',
  'Tide Otter',
  'Sand Puffin',
  'Wave Finch',
  'Moss Turtle',
  'Glow Moth',
  'Reef Star',
] as const

export const MODULE_ORDER: ModuleId[] = [
  'share',
  'passwords',
  'fakes',
  'kindness',
  'help',
]

export const modules: ModuleContent[] = [
  {
    id: 'share',
    title: "Privy's Cove",
    shortTitle: 'Share with Care',
    subtitle: 'Some things stay private!',
    host: 'privy',
    badgeName: 'Privacy Shell',
    badgeEmoji: '🐚',
    mapLabel: 'Cove',
    color: '#00B39A',
    lesson: [
      {
        id: 's1',
        character: 'shieldo',
        title: 'Welcome to Cyber Isle!',
        text: 'Hi! I am Shieldo. On Cyber Isle we learn how to stay safe when we use tablets, phones, and games.',
        tip: 'Cyber safety means looking after yourself and your secrets online.',
      },
      {
        id: 's2',
        character: 'privy',
        title: 'Meet Privy',
        text: 'I am Privy the lock-turtle. I protect private treasure — things that belong only to you and your family.',
      },
      {
        id: 's3',
        character: 'privy',
        title: 'What is private?',
        text: 'Your full name, home address, school name, phone number, and passwords are private. Keep them in your shell!',
        tip: 'If you are not sure, ask a grown-up before sharing.',
      },
      {
        id: 's4',
        character: 'privy',
        title: 'Try a sort!',
        text: 'Tap each item and decide: Keep Private, OK to Share, or Ask First.',
        interactive: 'demo-sort',
      },
      {
        id: 's5',
        character: 'privy',
        title: 'You are ready!',
        text: 'Great work! Next, practice sorting treasure chests in the cove game.',
      },
    ],
    quiz: [
      {
        id: 'sq1',
        prompt: 'Which should stay private?',
        choices: ['Your favorite color', 'Your home address', 'That you like cats'],
        correctIndex: 1,
        feedbackCorrect: 'Yes! Addresses stay private.',
        feedbackWrong: 'Home addresses are private treasure — keep them safe.',
      },
      {
        id: 'sq2',
        prompt: 'A new game friend asks for your school name. What do you do?',
        choices: ['Tell them right away', 'Ask a trusted adult first', 'Share a photo of the school'],
        correctIndex: 1,
        feedbackCorrect: 'Perfect — ask first!',
        feedbackWrong: 'School names are private. Ask a grown-up.',
      },
      {
        id: 'sq3',
        prompt: 'OK to share with friends?',
        choices: ['Your password', 'That you love soccer', 'Your phone number'],
        correctIndex: 1,
        feedbackCorrect: 'Likes and hobbies are usually fine to share.',
        feedbackWrong: 'Passwords and phone numbers stay private!',
      },
      {
        id: 'sq4',
        prompt: 'Someone online asks where you live. Best choice?',
        choices: ['Tell them the street', 'Keep it private and tell a grown-up', 'Guess a fake address'],
        correctIndex: 1,
        feedbackCorrect: 'Brave and smart — tell a grown-up.',
        feedbackWrong: 'Never share your address. Tell a trusted adult.',
      },
    ],
  },
  {
    id: 'passwords',
    title: "Keyora's Tower",
    shortTitle: 'Secret Keys',
    subtitle: 'Strong keys protect your treasure!',
    host: 'keyora',
    badgeName: 'Key Spark',
    badgeEmoji: '🔑',
    mapLabel: 'Tower',
    color: '#FFD400',
    unlockAfter: 'share',
    lesson: [
      {
        id: 'p1',
        character: 'keyora',
        title: 'Meet Keyora',
        text: 'Buzz! I am Keyora the key-firefly. Passwords are secret keys that unlock your games and accounts.',
      },
      {
        id: 'p2',
        character: 'keyora',
        title: 'Weak keys break easily',
        text: 'Short passwords like 1234 or your name are easy for tricksters to guess. Weak keys are like paper locks!',
      },
      {
        id: 'p3',
        character: 'keyora',
        title: 'Strong keys are long & silly',
        text: 'A strong password mixes words into a silly phrase, like BlueBananaDances! Longer is stronger.',
        tip: 'Only share passwords with trusted adults who help you.',
      },
      {
        id: 'p4',
        character: 'keyora',
        title: 'Build a silly key',
        text: 'Tap picture tiles to build a strong passphrase. Watch the strength meter glow!',
        interactive: 'demo-password',
      },
      {
        id: 'p5',
        character: 'keyora',
        title: 'Keep the key secret',
        text: 'Never tell friends your password. If someone asks for it online — that is a trick. Tell Beacon!',
      },
    ],
    quiz: [
      {
        id: 'pq1',
        prompt: 'Which password is stronger?',
        choices: ['abc123', 'SunnyTigerJumps!42', 'password'],
        correctIndex: 1,
        feedbackCorrect: 'Long and silly wins!',
        feedbackWrong: 'Pick the long silly phrase — it is much harder to guess.',
      },
      {
        id: 'pq2',
        prompt: 'Who can know your password?',
        choices: ['Everyone in class', 'A trusted adult who helps you', 'A new online friend'],
        correctIndex: 1,
        feedbackCorrect: 'Trusted grown-ups only!',
        feedbackWrong: 'Keep passwords secret — except from trusted adults.',
      },
      {
        id: 'pq3',
        prompt: 'Should you reuse one password everywhere?',
        choices: ['Yes, it is easier', 'No — use different strong keys', 'Only for games'],
        correctIndex: 1,
        feedbackCorrect: 'Different keys for different doors!',
        feedbackWrong: 'If one key leaks, all doors open. Use different passwords.',
      },
      {
        id: 'pq4',
        prompt: 'A message says “Send your password to win a prize!”',
        choices: ['Send it fast', 'Ignore it and tell a grown-up', 'Change one letter and send'],
        correctIndex: 1,
        feedbackCorrect: 'That is a trick — tell a grown-up.',
        feedbackWrong: 'Real prizes never need your password.',
      },
    ],
  },
  {
    id: 'fakes',
    title: "Spotter's River",
    shortTitle: "Don't Fall for Fake",
    subtitle: 'Tricks can look friendly!',
    host: 'spotter',
    badgeName: 'Sharp Eyes',
    badgeEmoji: '🔎',
    mapLabel: 'River',
    color: '#FF4D3A',
    unlockAfter: 'passwords',
    lesson: [
      {
        id: 'f1',
        character: 'spotter',
        title: 'Meet Spotter',
        text: 'Hoo! I am Spotter the lens-owl. Some messages online are tricks that try to hook your info.',
      },
      {
        id: 'f2',
        character: 'spotter',
        title: 'Computer germs',
        text: 'Clicking bad links or free-prize pop-ups can make a device “sick,” like catching germs. Ask before you click!',
        tip: 'If it sounds too good to be true — it probably is.',
      },
      {
        id: 'f3',
        character: 'spotter',
        title: 'Traffic light thinking',
        text: 'Green = safe & known. Yellow = ask a grown-up. Red = stop! Do not click.',
        interactive: 'demo-traffic',
      },
      {
        id: 'f4',
        character: 'spotter',
        title: 'Spot the signs',
        text: 'Watch for weird spelling, urgent “NOW!” messages, free prizes, and strangers asking for secrets.',
      },
      {
        id: 'f5',
        character: 'spotter',
        title: 'Practice time',
        text: 'In the river game, tap the fishy messages before they hook you!',
      },
    ],
    quiz: [
      {
        id: 'fq1',
        prompt: 'A pop-up says “FREE phone! Click now!” What color?',
        choices: ['Green — click it', 'Yellow/Red — ask or stop', 'Blue — ignore colors'],
        correctIndex: 1,
        feedbackCorrect: 'Too-good prizes are usually tricks.',
        feedbackWrong: 'Free prize pop-ups are red flags — do not click.',
      },
      {
        id: 'fq2',
        prompt: 'Your parent texts you from their known number. That is usually…',
        choices: ['Green — known and trusted', 'Red — always fake', 'A computer germ'],
        correctIndex: 0,
        feedbackCorrect: 'Known trusted contacts are safer.',
        feedbackWrong: 'Messages from people you know are usually safer — still ask if unsure.',
      },
      {
        id: 'fq3',
        prompt: 'A stranger says “I am your teacher — send your password.”',
        choices: ['Send it', 'Stop and tell a grown-up', 'Ask for their address'],
        correctIndex: 1,
        feedbackCorrect: 'Teachers never need your password that way.',
        feedbackWrong: 'That is a trick. Tell a trusted adult.',
      },
      {
        id: 'fq4',
        prompt: 'Weird link with spelling mistakes. Best move?',
        choices: ['Click to see', 'Do not click — ask an adult', 'Forward to friends'],
        correctIndex: 1,
        feedbackCorrect: 'Spotter is proud!',
        feedbackWrong: 'Weird links can carry computer germs. Ask first.',
      },
    ],
  },
  {
    id: 'kindness',
    title: "Spark's Meadow",
    shortTitle: 'Be Kind Online',
    subtitle: 'Words travel through screens too!',
    host: 'spark',
    badgeName: 'Kind Glow',
    badgeEmoji: '✨',
    mapLabel: 'Meadow',
    color: '#FF5A8A',
    unlockAfter: 'fakes',
    lesson: [
      {
        id: 'k1',
        character: 'spark',
        title: 'Meet Spark',
        text: 'Hello! I am Spark the star-cloud. Being kind online is just as important as being kind at school.',
      },
      {
        id: 'k2',
        character: 'spark',
        title: 'Words leave footprints',
        text: 'Mean messages can hurt feelings even when you cannot see a face. Kind words help everyone feel safe.',
      },
      {
        id: 'k3',
        character: 'spark',
        title: 'If someone is mean',
        text: 'You can: be kind, stop talking to them, block if you can, and always tell a trusted adult.',
        interactive: 'demo-kind',
      },
      {
        id: 'k4',
        character: 'spark',
        title: 'Stand up kindly',
        text: 'If you see unkind chat, you can support your friend and get help. You do not have to fix it alone.',
      },
      {
        id: 'k5',
        character: 'spark',
        title: 'Ready to glow',
        text: 'In the meadow game, send kind replies and send mean ones to Beacon for help!',
      },
    ],
    quiz: [
      {
        id: 'kq1',
        prompt: 'Someone writes something mean in a game chat. Best first step?',
        choices: ['Write something meaner', 'Stop, and tell a trusted adult', 'Share their password'],
        correctIndex: 1,
        feedbackCorrect: 'Brave and kind!',
        feedbackWrong: 'Do not fight fire with fire — get grown-up help.',
      },
      {
        id: 'kq2',
        prompt: 'A kind reply sounds like…',
        choices: ['“You are silly and dumb”', '“Nice try — want to play again?”', '“I will hack you”'],
        correctIndex: 1,
        feedbackCorrect: 'Kind words keep the meadow bright.',
        feedbackWrong: 'Choose words you would say face to face.',
      },
      {
        id: 'kq3',
        prompt: 'True or false: Online words cannot hurt.',
        choices: ['True', 'False — words can hurt', 'Only on weekends'],
        correctIndex: 1,
        feedbackCorrect: 'Feelings are real online too.',
        feedbackWrong: 'Screens do not stop hurt feelings.',
      },
      {
        id: 'kq4',
        prompt: 'Your friend is being teased online. You can…',
        choices: ['Join the teasing', 'Support them and tell an adult', 'Ignore forever and never help'],
        correctIndex: 1,
        feedbackCorrect: 'Friends help friends — and grown-ups help too.',
        feedbackWrong: 'Support your friend and get adult help.',
      },
    ],
  },
  {
    id: 'help',
    title: "Beacon's Lookout",
    shortTitle: 'Ask for Help',
    subtitle: 'Brave means telling a grown-up!',
    host: 'beacon',
    badgeName: 'Brave Compass',
    badgeEmoji: '🧭',
    mapLabel: 'Lookout',
    color: '#2F6FED',
    unlockAfter: 'kindness',
    lesson: [
      {
        id: 'h1',
        character: 'beacon',
        title: 'Meet Beacon',
        text: 'I am Beacon the compass-moth. Asking for help is brave — not babyish. Grown-ups are your safety lights.',
      },
      {
        id: 'h2',
        character: 'beacon',
        title: 'When to tell',
        text: 'Tell a trusted adult if something feels weird, scary, confusing, or too good to be true.',
        interactive: 'demo-help',
      },
      {
        id: 'h3',
        character: 'beacon',
        title: 'Who can help?',
        text: 'A parent, caregiver, teacher, or another grown-up you trust. Keep asking until someone listens.',
      },
      {
        id: 'h4',
        character: 'shieldo',
        title: 'You are a Cyber Defender!',
        text: 'You learned to share with care, use strong keys, spot tricks, be kind, and ask for help. Amazing!',
      },
      {
        id: 'h5',
        character: 'beacon',
        title: 'Last challenge',
        text: 'Finish the lookout game and quiz to earn your Brave Compass badge!',
      },
    ],
    quiz: [
      {
        id: 'hq1',
        prompt: 'A stranger asks to video chat alone. You should…',
        choices: ['Say yes', 'Tell a trusted adult', 'Give your address first'],
        correctIndex: 1,
        feedbackCorrect: 'Beacon lights the way!',
        feedbackWrong: 'Never meet or chat alone with strangers — tell a grown-up.',
      },
      {
        id: 'hq2',
        prompt: 'You clicked something and the screen looks weird. Next?',
        choices: ['Keep clicking', 'Tell a grown-up right away', 'Hide the tablet'],
        correctIndex: 1,
        feedbackCorrect: 'Grown-ups can help fix it.',
        feedbackWrong: 'Do not panic alone — ask for help.',
      },
      {
        id: 'hq3',
        prompt: 'Asking for help means you are…',
        choices: ['Brave and smart', 'In trouble forever', 'Bad at games'],
        correctIndex: 0,
        feedbackCorrect: 'Brave means talk it out!',
        feedbackWrong: 'Asking for help is a superpower.',
      },
      {
        id: 'hq4',
        prompt: 'Which mixes ALL Cyber Isle skills?',
        choices: [
          'Share secrets with strangers',
          'Keep private info safe, spot tricks, be kind, ask adults',
          'Use 1234 everywhere',
        ],
        correctIndex: 1,
        feedbackCorrect: 'You are Internet Awesome!',
        feedbackWrong: 'Remember: private, strong keys, spot fakes, kindness, ask help.',
      },
      {
        id: 'hq5',
        prompt: 'If a grown-up does not listen the first time…',
        choices: ['Give up', 'Keep asking another trusted adult', 'Post about it publicly'],
        correctIndex: 1,
        feedbackCorrect: 'Keep seeking help until you are heard.',
        feedbackWrong: 'Find another trusted adult who can help.',
      },
    ],
  },
]

export function getModule(id: ModuleId): ModuleContent {
  const mod = modules.find((m) => m.id === id)
  if (!mod) throw new Error(`Unknown module: ${id}`)
  return mod
}

export function isModuleUnlocked(
  id: ModuleId,
  completedQuizzes: ModuleId[],
): boolean {
  const mod = getModule(id)
  if (!mod.unlockAfter) return true
  return completedQuizzes.includes(mod.unlockAfter)
}
