import type { ModuleContent, ModuleId } from './types'

export const NICKNAMES = [
  'Sunny Crab',
  'Coral Fox',
  'Tide Otter',
  'Sand Puffin',
  'Wave Finch',
  'Moss Turtle',
  'Glow Moth',
  'Reef Star',
] as const

export const MODULE_ORDER: ModuleId[] = [
  'share',
  'passwords',
  'fakes',
  'kindness',
  'help',
]

export const modules: ModuleContent[] = [
  {
    id: 'share',
    title: "Privy's Cove",
    shortTitle: 'Share with Care',
    subtitle: 'Some things stay in your shell!',
    host: 'privy',
    badgeName: 'Privacy Shell',
    badgeEmoji: '🐚',
    mapLabel: 'Cove',
    color: '#00B39A',
    gameName: 'Treasure Crossing',
    gameBlurb: 'Hop to the vault. Dodge private trucks. Ride OK-to-share logs.',
    lesson: [
      {
        id: 's1',
        character: 'shieldo',
        title: 'Welcome to Cyber Isle!',
        text: 'Hi! I am Shieldo. Tablets, games, and chats can send a message to lots of people at once — even people you have never met.',
        tip: 'Think before you tap Send.',
      },
      {
        id: 's2',
        character: 'privy',
        title: 'Meet Privy',
        text: 'I am Privy the lock-turtle. A secret in a locked shell is different from shouting on the playground. The internet is a very big playground.',
      },
      {
        id: 's3',
        character: 'privy',
        title: 'Lock these up',
        text: 'A photo of your house, the street on your mailbox, and your real last name are private. They help a stranger find you in real life.',
        tip: 'If a picture shows your front door or street sign, keep it in the shell.',
      },
      {
        id: 's4',
        character: 'privy',
        title: 'Fine to cheer about',
        text: 'You can usually share hobbies: “I like pancakes,” “I build robots,” or a drawing of a dragon. Those do not tell people where you live.',
      },
      {
        id: 's5',
        character: 'privy',
        title: 'Ask first',
        text: 'A class photo, a school hoodie with the school name, or a video from your kitchen might show more than you meant. Check with a grown-up before you post those.',
      },
      {
        id: 's6',
        character: 'privy',
        title: 'Quick sort',
        text: 'Try four new treasures. Put each in Keep Private, OK to Share, or Ask First.',
        interactive: 'demo-sort',
      },
    ],
    quiz: [
      {
        id: 'sq1',
        prompt: 'In a tablet game, CoolCat99 types “What street do you live on?” What do you do?',
        choices: [
          'Type the street so they can “visit”',
          'Do not answer, and show a grown-up the chat',
          'Send a photo of the mailbox instead',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Street names stay in your shell. Showing a grown-up is smart.',
        feedbackWrong: 'Do not tell your street. Show a trusted adult the chat.',
      },
      {
        id: 'sq2',
        prompt: 'Which is safer to post on a kid art app?',
        choices: [
          'A photo of your clay dinosaur',
          'A photo of your front door with the house number',
          'A selfie in front of your school sign',
        ],
        correctIndex: 0,
        feedbackCorrect: 'Art you made is usually fine. Doors and school signs give clues.',
        feedbackWrong: 'House numbers and school signs can show where you are.',
      },
      {
        id: 'sq3',
        prompt: 'What’s the trick? A new teammate says “Tell me your last name so I can add you to the school soccer list.”',
        choices: [
          'They must be the coach, so share it',
          'Real lists go through a parent or teacher, not a random chat',
          'Share a nickname and the last name',
        ],
        correctIndex: 1,
        feedbackCorrect: 'School lists are grown-up jobs — not secret chat jobs.',
        feedbackWrong: 'A stranger in chat should not collect last names.',
      },
      {
        id: 'sq4',
        prompt: 'You almost typed your street into a “free stickers” box. Who can you tell?',
        choices: [
          'Only the sticker website',
          'A parent, caregiver, or teacher you trust',
          'Everyone in the game lobby',
        ],
        correctIndex: 1,
        feedbackCorrect: 'A trusted adult can help you close the box safely.',
        feedbackWrong: 'Tell a grown-up you trust — not the whole lobby.',
      },
    ],
  },
  {
    id: 'passwords',
    title: "Keyora's Tower",
    shortTitle: 'Secret Keys',
    subtitle: 'Long silly keys beat tiny ones!',
    host: 'keyora',
    badgeName: 'Key Spark',
    badgeEmoji: '🔑',
    mapLabel: 'Tower',
    color: '#FFD400',
    gameName: 'Key Blaster',
    gameBlurb: 'Blast weak keys like 1234. Do not shoot long silly keys!',
    lesson: [
      {
        id: 'p1',
        character: 'keyora',
        title: 'Meet Keyora',
        text: 'Buzz! I am Keyora the key-firefly. A password is a key for your game or tablet — not a toy to show friends.',
      },
      {
        id: 'p2',
        character: 'keyora',
        title: 'Tiny keys snap',
        text: 'Guessing starts with 1234, abc, and a pet’s name. Short keys snap like paper locks. Tricksters try those first.',
      },
      {
        id: 'p3',
        character: 'keyora',
        title: 'Silly and long',
        text: 'Mash four words into a goofy phrase, like PizzaMoonRocketSeven. Longer mixed-up words are much harder to guess.',
        tip: 'A picture story in your head helps you remember it.',
      },
      {
        id: 'p4',
        character: 'keyora',
        title: 'Build a phrase',
        text: 'Tap tiles to stack a long silly key. Watch the meter glow when it gets long enough.',
        interactive: 'demo-password',
      },
      {
        id: 'p5',
        character: 'keyora',
        title: 'Who may know?',
        text: 'A parent or caregiver who helps you log in may know the key. A pal in chat who says “I’m stuck — type it here” is not allowed.',
      },
      {
        id: 'p6',
        character: 'keyora',
        title: 'One door, one key',
        text: 'If the same phrase opens your art app and your mail game, one leak opens both. Different doors need different keys.',
      },
    ],
    quiz: [
      {
        id: 'pq1',
        prompt: 'Which key is stronger?',
        choices: ['0909', 'MapleToastWiggle4', 'abc'],
        correctIndex: 1,
        feedbackCorrect: 'Long and silly wins. Short number keys snap.',
        feedbackWrong: 'Pick the mashed-up words — they are harder to guess.',
      },
      {
        id: 'pq2',
        prompt: 'Chat says “Type your password here or the game will delete your pet.” What do you do?',
        choices: [
          'Type it fast to save the pet',
          'Do not type it. Show a grown-up the message',
          'Type it with one letter changed',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Real games do not ask for your key in chat.',
        feedbackWrong: 'That is a scare trick. Never type a password in chat.',
      },
      {
        id: 'pq3',
        prompt: 'What’s the trick? A pop-up says “We are the game team. Confirm your key to keep your skins.”',
        choices: [
          'It looks official, so type the key',
          'The real app already knows you — this pop-up is fishing',
          'Send a screenshot of the key',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Fake “game teams” do not need you to retype your key.',
        feedbackWrong: 'Close it and tell a grown-up. Do not confirm keys in pop-ups.',
      },
      {
        id: 'pq4',
        prompt: 'Your tablet asks you to make a new key and the spelling is tricky. Who can you tell?',
        choices: [
          'A trusted adult who can help you type',
          'A new friend in the lobby',
          'The whole class group chat',
        ],
        correctIndex: 0,
        feedbackCorrect: 'Helpers at home or school can know the key. Lobby friends cannot.',
        feedbackWrong: 'Only a trusted adult who helps you log in.',
      },
    ],
  },
  {
    id: 'fakes',
    title: "Spotter's River",
    shortTitle: "Don't Fall for Fake",
    subtitle: 'Prizes and panic can be traps!',
    host: 'spotter',
    badgeName: 'Sharp Eyes',
    badgeEmoji: '🔎',
    mapLabel: 'River',
    color: '#FF4D3A',
    gameName: 'Trick Invaders',
    gameBlurb: 'Zap fake prize pop-ups. Let real family and class notes land.',
    lesson: [
      {
        id: 'f1',
        character: 'spotter',
        title: 'Meet Spotter',
        text: 'Hoo! I am Spotter the lens-owl. Some notes pretend to be prizes, teachers, or even your device “crying for help.”',
      },
      {
        id: 'f2',
        character: 'spotter',
        title: 'Pop-up prizes',
        text: '“FREE headphones if you tap NOW!” Real shops do not dump prizes on your homework app. Urgency is the bait.',
      },
      {
        id: 'f3',
        character: 'spotter',
        title: 'Weird links',
        text: 'Watch for misspellings, extra letters, and names like clik-prize-now. A messy link is a hook. Do not tap it.',
      },
      {
        id: 'f4',
        character: 'spotter',
        title: 'Fake teacher, fake pal',
        text: '“It’s Ms. Lee — send your tablet PIN.” Real teachers use the class app your family already set up, not a surprise chat.',
      },
      {
        id: 'f5',
        character: 'spotter',
        title: 'Computer germs',
        text: 'One tap on a sparkly banner can flood the screen with ads or slow the tablet. Freeze. Do not keep tapping. Get a grown-up.',
        tip: 'You did not “break it forever.” Adults can help clean it up.',
      },
      {
        id: 'f6',
        character: 'spotter',
        title: 'Traffic-light brain',
        text: 'Green = known and calm. Yellow = ask. Red = stop. Color this surprise message.',
        interactive: 'demo-traffic',
      },
    ],
    quiz: [
      {
        id: 'fq1',
        prompt: 'What’s the trick? “Your tablet is sick! Call this number and read them your password.”',
        choices: [
          'Call so the tablet gets better',
          'No — freeze and tell a grown-up. Nobody needs your password by phone',
          'Read the password but not the number',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Scare-and-call tricks want your key. Adults handle “sick” screens.',
        feedbackWrong: 'Do not call mystery numbers or read passwords out loud.',
      },
      {
        id: 'fq2',
        prompt: 'A chat name looks like your cousin, but they ask for a photo of your house key. What do you do?',
        choices: [
          'Send it — cousins are safe',
          'Stop. Real family would not ask that. Show a grown-up',
          'Send a drawing of the key',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Names can be copied. Weird asks mean stop and tell.',
        feedbackWrong: 'A copied name is still a stranger if the ask is weird.',
      },
      {
        id: 'fq3',
        prompt: 'Which is safer?',
        choices: [
          'Homework posted on your class site',
          'An email: “Open this for tonight’s worksheet prize”',
          'A pop-up: “Download mystery helper now”',
        ],
        correctIndex: 0,
        feedbackCorrect: 'The class site your teacher uses is the calm, known path.',
        feedbackWrong: 'Prize emails and mystery downloads are hooks.',
      },
      {
        id: 'fq4',
        prompt: 'You tapped a sparkly banner and now ads will not stop. Who can you tell?',
        choices: [
          'Nobody — hide the tablet',
          'A parent, caregiver, or teacher who can help pause it',
          'The banner company in the ad',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Grown-ups can stop the flood. You are not in trouble for telling.',
        feedbackWrong: 'Do not hide it. A trusted adult can help.',
      },
    ],
  },
  {
    id: 'kindness',
    title: "Spark's Meadow",
    shortTitle: 'Be Kind Online',
    subtitle: 'Words land in someone’s day!',
    host: 'spark',
    badgeName: 'Kind Glow',
    badgeEmoji: '✨',
    mapLabel: 'Meadow',
    color: '#FF5A8A',
    gameName: 'Kindness Invaders',
    gameBlurb: 'Blast mean meteors with KIND stars. Catch help-a-friend tokens.',
    lesson: [
      {
        id: 'k1',
        character: 'spark',
        title: 'Meet Spark',
        text: 'Hello! I am Spark the star-cloud. A message can land in someone’s pocket even if you never see their face.',
      },
      {
        id: 'k2',
        character: 'spark',
        title: 'After a missed shot',
        text: '“You ruined it” in game chat can feel like a shove. You cannot take a shove back with a bigger shove — that makes two hurts.',
      },
      {
        id: 'k3',
        character: 'spark',
        title: 'Support a friend',
        text: 'A quiet “Want to team up next round?” or sitting with them later helps more than a crowd watching. You do not need a big speech.',
        interactive: 'demo-kind',
      },
      {
        id: 'k4',
        character: 'spark',
        title: 'Don’t pile on',
        text: 'Five people joking still means the sixth joke can sting. If a roast train starts, skip it. Leaving the pile is brave.',
      },
      {
        id: 'k5',
        character: 'spark',
        title: 'When it keeps going',
        text: 'If mean notes keep coming or your tummy feels twisty, show a grown-up the chat. You do not have to fix a whole group alone.',
      },
    ],
    quiz: [
      {
        id: 'kq1',
        prompt: 'Someone laughs at your username after you lose. What do you do?',
        choices: [
          'Invent a meaner nickname for them',
          'Leave the chat or mute, and tell a grown-up if it keeps going',
          'Post their real name to “even it out”',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Step back. Mean-for-mean makes a bigger mess.',
        feedbackWrong: 'Do not strike back with names. Pause and get help if it continues.',
      },
      {
        id: 'kq2',
        prompt: 'Which is kinder?',
        choices: [
          'Adding one more roast in the group thread',
          'Sending a private “You okay? Want to play something else?”',
          'Sharing their drawing so more people can laugh',
        ],
        correctIndex: 1,
        feedbackCorrect: 'A private check-in is support. Pile-ons are not jokes to everyone.',
        feedbackWrong: 'Support happens beside a friend, not on top of them.',
      },
      {
        id: 'kq3',
        prompt: 'What’s the trick? A group chat says “If you’re cool you’ll roast them too so they leave the game.”',
        choices: [
          'Roast so you stay in the group',
          'That is pressure to pile on — skip it and tell an adult if needed',
          'Roast once, then apologize later',
        ],
        correctIndex: 1,
        feedbackCorrect: '“Prove you’re cool” is a trap to make the pile bigger.',
        feedbackWrong: 'Cool is skipping the roast train.',
      },
      {
        id: 'kq4',
        prompt: 'Your friend got a mean voice note after school and wants to hide it. Who can you tell?',
        choices: [
          'Nobody — secrets about hurt stay secret',
          'A trusted adult, even if your friend is scared',
          'The whole class so they can “vote”',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Hiding mean notes lets them grow. A grown-up can help both of you.',
        feedbackWrong: 'Tell a trusted adult. You can still be a kind friend while getting help.',
      },
    ],
  },
  {
    id: 'help',
    title: "Beacon's Lookout",
    shortTitle: 'Ask for Help',
    subtitle: 'Brave means keep telling!',
    host: 'beacon',
    badgeName: 'Brave Compass',
    badgeEmoji: '🧭',
    mapLabel: 'Lookout',
    color: '#2F6FED',
    gameName: 'Beacon Run',
    gameBlurb: 'Grab tell-a-grown-up lanterns. Dodge “keep it secret” trucks. Reach the lighthouse.',
    lesson: [
      {
        id: 'h1',
        character: 'beacon',
        title: 'Meet Beacon',
        text: 'I am Beacon the compass-moth. That “this feels weird” flutter in your tummy is a signal — like a lighthouse ping. It is not being a baby.',
      },
      {
        id: 'h2',
        character: 'beacon',
        title: 'Keep asking',
        text: 'If the first grown-up is cooking, on a call, or says “later,” try again. A teacher, coach, or another caregiver can listen too.',
        interactive: 'demo-help',
      },
      {
        id: 'h3',
        character: 'beacon',
        title: 'Mix it together',
        text: 'Weird chat + a private ask + a mean pile-on is a lot. Pause the game. You do not have to solve the whole mix yourself.',
      },
      {
        id: 'h4',
        character: 'shieldo',
        title: 'Cyber Defender',
        text: 'You practiced five skills: lock private clues, use long keys, spot prize traps, skip roast trains, and follow the weird-feeling ping.',
      },
      {
        id: 'h5',
        character: 'beacon',
        title: 'Rescue run',
        text: 'Next, guide a lost spark to my lookout. Grab lanterns that say tell a grown-up. Dodge clouds that say keep it secret.',
      },
    ],
    quiz: [
      {
        id: 'hq1',
        prompt: 'Someone you only know from a building game wants a video call after bedtime. What do you do?',
        choices: [
          'Say yes if they seem nice',
          'No call. Tell a trusted adult about the ask',
          'Call but keep the camera off and share your street',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Game-only pals stay in the game. Video is a grown-up decision.',
        feedbackWrong: 'Do not video-chat people you only know online. Tell a grown-up.',
      },
      {
        id: 'hq2',
        prompt: 'After one tap, the screen goes swirly and buttons you do not know pop up. Next?',
        choices: [
          'Keep tapping to “fix” it',
          'Put it down and get a grown-up right away',
          'Throw the tablet so it resets',
        ],
        correctIndex: 1,
        feedbackCorrect: 'More taps can make swirls worse. Adults know the pause steps.',
        feedbackWrong: 'Stop tapping. Get help. You are not in trouble for asking.',
      },
      {
        id: 'hq3',
        prompt: 'Asking for help means you are…',
        choices: [
          'Brave and using your signal',
          'Banned from games forever',
          'Too little for tablets',
        ],
        correctIndex: 0,
        feedbackCorrect: 'Beacon is proud. Talking is a superpower.',
        feedbackWrong: 'Asking is brave — not a ban, not “too little.”',
      },
      {
        id: 'hq4',
        prompt: 'Which plan uses every Cyber Isle skill?',
        choices: [
          'Post the house photo, reuse 0909, tap prize links, roast back, stay quiet',
          'Skip private clues, keep long keys, ignore prize panic, skip pile-ons, tell an adult',
          'Tell a stranger your PIN if they pinky-promise',
        ],
        correctIndex: 1,
        feedbackCorrect: 'That mix is Internet Awesome.',
        feedbackWrong: 'Lock clues, strong keys, skip traps, skip roasts, tell someone.',
      },
      {
        id: 'hq5',
        prompt: 'The first grown-up says “not now” and walks away. Then what?',
        choices: [
          'Give up — you tried',
          'Ask another trusted adult, or try again when they can listen',
          'Post the problem on a public app',
        ],
        correctIndex: 1,
        feedbackCorrect: 'Keep seeking a listener. Lighthouses have more than one lamp.',
        feedbackWrong: 'Try another trusted adult. Do not post it for the whole internet.',
      },
    ],
  },
]

export function getModule(id: ModuleId): ModuleContent {
  const mod = modules.find((m) => m.id === id)
  if (!mod) throw new Error(`Unknown module: ${id}`)
  return mod
}
